name: tag
on:
  push:
    tags: ['*']

jobs:

  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo variables
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "GITHUB_REF_TYPE=${GITHUB_REF_TYPE}"
          echo "github.ref=${{ github.ref }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.ref_type=${{ github.ref_type }}"

  trigger:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: trigger manual workflow
        run: |
          wfid=manual.yml
          curl -L -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"ref":"master","inputs":{"tag":"${{ github.ref_name }}"}}' \
              "${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/${wfid}/dispatches"

        # env:
        #   GH_TOKEN: ${{ github.token }}
          # `gh workflow` requires we clone the project.
          # gh workflow run manual.yml -f tag=${GITHUB_REF_NAME}
