name: tag
on:
  push:
    tags: ['*']

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: echo variables
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "GITHUB_REF_TYPE=${GITHUB_REF_TYPE}"
          echo "github.ref=${{ github.ref }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.ref_type=${{ github.ref_type }}"
      - name: trigger manual workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run manual.yml -f tag=${GITHUB_REF_NAME}
