name: test
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  environment:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - macos
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - name: install GCC on macOS
        if: startsWith(matrix.platform, 'macos')
        run: |
          brew install gcc@13
          type gcc-13
          type g++-13
      - name: GCC
        run: |
          type gcc
          gcc --version
          type g++
          g++ --version
          ls /usr/bin/gcc*
      - name: Clang
        run: |
          type clang
          clang --version
          type clang++
          clang++ --version
          ls /usr/bin/clang*

  cmake:
    runs-on: ubuntu-latest
    steps:
      - name: check CMake before
        run: |
          cmake --version || true
      - name: install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.20.x'
      - name: check CMake after
        run: |
          cmake --version || true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: succeeds
        run: |
          true
      - name: fails
        continue-on-error: true
        run: |
          echo ::error title=Error Title::The error message.
          false
      - name: continues
        run: |
          echo 'Hello, world!'
